repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.12.0
#    hooks:
##      - id: isort
#  - repo: https://github.com/psf/black
#    rev: 23.3.0
#    hooks:
#      - id: black
#        language_version: python3.9
#        exclude: ^.*\b(migrations)\b.*$
